project_id = "zovhwryzsujevrnakfcw"

[functions.data-api]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.manage-booking]
verify_jwt = false
